### ISSUE TITLE
Error while importing new xml within wro.xml

### ISSUE THREAD

**Issue by deepali311** [alexo/wro4j#225]
Hi,

I am working with Ant , done the required configuration.
When i try to import another file placed in \web\webroot\WEB-INF:

<import>classpath:WEB-INF/wro_common.xml</import>
or
<import>classpath:wro_common.xml</import>

And it throws below exception		

 [exec] processing group: germany_styles.css
     [exec] Error while creating the modelNo valid model was found!
     [exec]
     [exec]
     [exec] ro.isdc.wro.WroRuntimeException: Cannot build model from XML
     [exec]
     [exec] =======================================
     [exec]     at ro.isdc.wro.model.factory.XmlModelFactory.createDocument(XmlModelFactory.java:154)
     [exec]     at ro.isdc.wro.model.factory.XmlModelFactory.create(XmlModelFactory.java:130)
     [exec]     at ro.isdc.wro.model.factory.XmlModelFactory.processImports(XmlModelFactory.java:215)
     [exec]     at ro.isdc.wro.model.factory.XmlModelFactory.create(XmlModelFactory.java:134)
     [exec]     at ro.isdc.wro.model.factory.XmlModelFactory.create(XmlModelFactory.java:50)
     [exec] USAGE       at ro.isdc.wro.extensions.model.factory.SmartWroModelFactory.create(SmartWroModelFactory.java:180)
     [exec]
     [exec]     at ro.isdc.wro.extensions.model.factory.SmartWroModelFactory.create(SmartWroModelFactory.java:36)
     [exec] =======================================
     [exec]     at ro.isdc.wro.model.factory.WroModelFactoryDecorator.create(WroModelFactoryDecorator.java:30)
     [exec]     at ro.isdc.wro.model.factory.ModelTransformerFactory.create(ModelTransformerFactory.java:47)
     [exec]     at ro.isdc.wro.model.factory.ModelTransformerFactory.create(ModelTransformerFactory.java:25)
     [exec]  --contextFolder PATH                          : Folder used as a root of the context relative resou
     [exec]                                                  rces. By default this is the user current folder.
     [exec]  --destinationFolder PATH                      : Where to store the processed result. By default use
     [exec]                                                  s the folder named [wro].
     [exec]  --parallel                                    : Turns on the parallel preProcessing of resources. T
     [exec]                                                  his value is false by default.
     [exec]  --postProcessors POST_PROCESSOR               : Comma separated list of post-processors
     [exec]  --targetGroups GROUPS                         : Comma separated value of the group names from wro.x
     [exec]                                                  ml to process. If none is provided, all groups will

**Comment by alexo** [comment]
Could you create this issue in [wro4j/wro4j](https://github.com/wro4j/wro4j/) - the new location of the project. Also, provide more details about the used version
